name: Build OurTransfert and Copy to OurTransfert-server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:         
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: clone and build OurTransfert
        run: git clone https://github.com/UrbsKali/OurTransfert;cd OurTransfert; npm i;npm run build
      - name: clone
        run: git clone https://github.com/UrbsKali/OurTransfert-server
      - name: build 2 
        run: cd OurTransfert-server;mkdir -p ui;cp -r ../OurTransfert/dist ./ui
      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build UI"
          git push
          
